# Azure Pipelines configuration for @coa/goldfish-mcp
# Simple, clean approach - no unnecessary complexity

trigger:
  branches:
    include:
      - main
      - develop

pool:
  name: 'Default'  # Local Windows agent pool

variables:
  nodeVersion: '20.x'
  packageName: '@coa/goldfish-mcp'

stages:
  - stage: BuildTest
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build, Lint, and Test'
        steps:
          # Setup Node.js
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(nodeVersion)

          # Install dependencies
          - script: npm ci
            displayName: 'Install dependencies'

          # Run linting
          - script: npm run lint
            displayName: 'Run linting'
            continueOnError: true

          # Build TypeScript
          - script: npm run build
            displayName: 'Build TypeScript'

          # Run tests with coverage
          - script: npm test -- --coverage
            displayName: 'Run tests with coverage'
            continueOnError: true

          # Publish test results
          - task: PublishTestResults@2
            displayName: 'Publish test results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'test-results.xml'
              failTaskOnFailedTests: false
            condition: always()

          # Publish code coverage
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish code coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: 'coverage/cobertura-coverage.xml'
              failIfCoverageEmpty: false
            condition: always()

  - stage: Publish
    displayName: 'Publish Package'
    dependsOn: BuildTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: PublishPackage
        displayName: 'Publish to npm feed'
        steps:
          # Setup Node.js
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(nodeVersion)

          # Install dependencies
          - script: npm ci
            displayName: 'Install dependencies'

          # Build for publishing
          - script: npm run build
            displayName: 'Build for publish'

          # Authenticate with Azure DevOps npm feed
          - task: npmAuthenticate@0
            displayName: 'Authenticate npm feed'
            inputs:
              workingFile: '.npmrc'

          # Bump version and publish
          - script: |
              # Get current version
              CURRENT_VERSION=$(node -p "require('./package.json').version")
              echo "Current version: $CURRENT_VERSION"
              
              # Parse version components
              MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
              MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
              PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
              
              # Increment patch version
              NEW_PATCH=$((PATCH + 1))
              NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
              
              echo "Publishing version: $NEW_VERSION"
              
              # Update version in package.json
              npm version $NEW_VERSION --no-git-tag-version
              
              # Publish to feed
              npm publish --registry https://pkgs.dev.azure.com/childrensal/_packaging/COA-NPM-Packages/npm/registry/
              
            displayName: 'Version and publish'
            
          # Save build artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifacts'
            inputs:
              pathToPublish: 'dist'
              artifactName: 'dist'